[package]
name = "saildb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sia = { path = "../sia/sia" }
sia = "0.0.4"
srpc = { path = "../srpc/srpc" }
serde = { version = "1" }
dashmap = "5"
